### ISSUE TITLE
OTP < 18 not supported

### ISSUE THREAD

**Issue by lrascao** [cabol/shards#13]
shards_owner_sup is making use of the newly introduced map support for supervisor child specs and flags (https://www.erlang.org/downloads/18.0), this prevents older versions from being able to use shards. Maybe co-existence could be possible by detecting the target OTP version and generating either the old tuple format or the new one.

**Comment by cabol** [comment]
@lrascao I think is fixed. Check out the master branch and let me know if we can close this issue. Thanks again :)!!

**Comment by lrascao** [comment]
works great! do you think you can release a new tag?
thanks!
