### ISSUE TITLE
file2tab,tab2file not working 

### ISSUE THREAD

**Issue by grizzly-monkey** [cabol/shards#33]
shards:new(live,[{scope, g},{nodes, [node()]}]).
shards:insert(live,{k2,val2}).   
true
shards:insert(live,{k4,val2}).   
true
shards:insert(live,{k23,val2}).   
true

 shards:lookup(live,k23).
[{k23,val2}]

shards:tab2list(live).            
** exception error: undefined function shards_dist:tab2list/2
(ejabberd@localhost)10> shards:tab2file(live,"/tmp/test").
** exception error: undefined function shards_dist:tab2file/3

above functions dont work.

from ets it does work.
ets:tab2list(live_2).
[{k2,val2}]

**Comment by cabol** [comment]
Hi @nOmi7 you're right, those functions are not implemented by `shards_dist` yet (currently only works for `shards_local`). Take a look to `shards_dist` module so you can check what functions are provided so far – `shards_dist` is still under development, only part of the ETS API is provided by now. And remember, any contribution is welcome :) !!!

**Comment by cabol** [comment]
@nOmi7 it should be working now, let me know if you have any issue, meanwhile I'll close this one (feel free to re-open it in case of some failure)
