### ISSUE TITLE
Missing support for keypos

### ISSUE THREAD

**Issue by edescourtis** [cabol/shards#44]
For people using records in `ets` tables, it is essential to support setting the `keypos`.

**Comment by cabol** [comment]
@edescourtis could you please elaborate more on that, why do you say it is not supported? In what case `keypos` doesn't work or it is not supported by `shards`, and it is supported normally by `ets`? I need more details, please.

**Comment by edescourtis** [comment]
When using records (tagged tuples) it is always the case that the key (used for lookups for example) is not stored at position 1 (typically the key would be at position 2). `keypos` is something mandatory to support records in `ets`.

It is of course supported by `ets` and doesn't work with `shards` otherwise I wouldn't have filed an issue. 

You are also missing `select_replace` see my branch in case you want to cherry-pick it.

**Comment by cabol** [comment]
Ok, I'll check it out, thanks!

**Comment by cabol** [comment]
I found the issue with `keypos`, I'll try to fix it as soon as I can, thanks again!

**Comment by edescourtis** [comment]
No thank you for making this library! I will definitely use it in the future.

**Comment by cabol** [comment]
Fixed on the master branch! Please try it out and let me know how it goes and if we can close the issue. For `select_replace` I will create another one.

**Comment by cabol** [comment]
I will close the issue, feel free to open it in case it doesn't work or you find something wrong with it.
