### ISSUE TITLE
Operation of the shards:info/2 does not match

### ISSUE THREAD

**Issue by voluntas** [cabol/shards#8]
Thank you for a nice library.

This is to report that the shards:info/2 is different from the ets:info/2 behavior.

```
> shards:info(mytab, name).
** exception error: bad argument
     in function  ets:lookup_element/3
        called as ets:lookup_element(mytab,'$shards_state',2)
...
> ets:info(mytab, name).
undefined
```

**Comment by cabol** [comment]
@voluntas thanks for the report, I'll take a look at it!!

**Comment by cabol** [comment]
Fixed, checkout the master branch. Let me know if everything is ok now.

> **Note:** This is the commit: https://github.com/cabol/shards/commit/e78edc45b3052e2f3fd350e4bbf81c8fb3e0094f.

**Comment by voluntas** [comment]
Now it works as expected. Thank you!
